spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:app_db}
    username: ${POSTGRES_USER:app_user}
    password: ${POSTGRES_PASSWORD:secure_password}
  jpa:
    hibernate:
      ddl-auto: create-drop
jwt:
  secret: ${JWT_SECRET:__dummy_build_secret__}
  expiration: 900000
  refresh:
    expiration: 604800000

admin:
  email: ${ADMIN_EMAIL:admin}
  password: ${ADMIN_PASSWORD:admin_password}

server:
  forward-headers-strategy: framework