spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:app_db}
    username: ${POSTGRES_USER:app_user}
    password: ${POSTGRES_PASSWORD:secure_password}
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: ${JWT_SECRET}
  expiration: 900000
  refresh:
    expiration: 604800000

admin:
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}

server:
  forward-headers-strategy: framework